/* 健康コンシェルジュ Ver1.1 商品読取 */
(()=>{
const healthRe={blood:/砂糖|果糖|ぶどう糖|水あめ|シロップ|炭水化物|糖質|デキストリン/i,liver:/砂糖|果糖|アルコール|酒精|植物油|油脂|ショートニング|バター|クリーム/i,uric:/レバー|煮干|かつお|いわし|魚介エキス|肉エキス|酵母エキス|白子|あん肝/i};
let scanner=null,worker=null,busy=false;
const setStatus=(id,text,kind="idle")=>{const e=$(id);e.textContent=text;e.className=`state ${kind}`};
const validJan=value=>{const jan=String(value||"").replace(/\D/g,"");if(![8,12,13,14].includes(jan.length))return false;const a=[...jan].map(Number),check=a.pop();let sum=0;for(let i=a.length-1,p=0;i>=0;i--,p++)sum+=a[i]*(p%2?1:3);return(10-sum%10)%10===check};
const form=()=>({jan:$("scanJan").value.replace(/\D/g,""),name:$("scanName").value.trim(),maker:$("scanMaker").value.trim(),category:$("scanCategory").value.trim(),ingredients:$("scanIngredients").value.trim(),allergens:$("scanAllergens").value.trim(),nutrition:$("scanNutrition").value.trim(),portion:$("scanPortion").value.trim(),source:$("scanSource").value.trim()});
function health(data){const text=`${data.ingredients} ${data.nutrition}`;return {blood:healthRe.blood.test(text)?"warn":"good",liver:/アルコール|酒精/.test(text)?"bad":healthRe.liver.test(text)?"warn":"good",uric:healthRe.uric.test(text)?"warn":"good"}}
function analyze(){const data=form(),h=health(data),b=badge(h.blood),l=badge(h.liver),u=badge(h.uric),tips=[];if(h.blood!=="good")tips.push("糖類・炭水化物と1回量を確認");if(h.liver!=="good")tips.push("糖質・脂質・アルコールの重なりに注意");if(h.uric!=="good")tips.push("魚介・肉・酵母エキス、飲酒、水分不足に注意");$("scanHealthResult").innerHTML=`<p><span class="badge ${b[1]}">血糖 ${b[0]}</span><span class="badge ${l[1]}">肝臓 ${l[0]}</span><span class="badge ${u[1]}">尿酸 ${u[0]}</span></p><p>${escapeHtml(tips.join("。")||"強い注意語は検出されませんでした。量と食べ合わせも確認してください。")}</p><p class="fine">原材料のキーワードによる参考判定です。診断・検査値予測ではありません。</p>`;return h}
function fill(p={}){$("scanJan").value=p.jan||p.code||"";$("scanName").value=p.name||"";$("scanMaker").value=p.maker||p.brands||"";$("scanCategory").value=p.category||p.categories||"";$("scanIngredients").value=p.ingredients||"";$("scanAllergens").value=p.allergens||"";$("scanNutrition").value=p.nutrition||"";$("scanPortion").value=p.portion||p.serving_size||"";$("scanSource").value=p.source||"商品ラベル（OCR・手入力）";analyze()}
function nutrition(p){const n=p.nutriments||{},a=[];[["エネルギー","energy-kcal","kcal"],["たんぱく質","proteins","g"],["脂質","fat","g"],["炭水化物","carbohydrates","g"],["糖類","sugars","g"],["食塩相当量","salt","g"]].forEach(([label,key,unit])=>{const v=n[`${key}_100g`];if(v!=null)a.push(`${label}：${v}${unit}（100g/ml当たり）`)});return a.join("\n")}
async function lookup(raw){const jan=String(raw||"").replace(/\D/g,"");$("janInput").value=jan;$("scanJan").value=jan;if(!validJan(jan)){setStatus("scanState","番号を確認","failure");return alert("JANコードの桁数またはチェックデジットが正しくありません。")}
 setStatus("scanState","商品検索中","working");$("productLookupResult").innerHTML='<div class="panel">商品情報を検索しています……</div>';
 const mine=state.customProducts.find(x=>String(x.jan||"")===jan);if(mine){fill(mine);setStatus("scanState","登録商品を表示","success");$("productLookupResult").innerHTML='<div class="panel save-success">✓ マイ商品DBから読み込みました。</div>';return}
 try{const url=`https://world.openfoodfacts.org/api/v2/product/${encodeURIComponent(jan)}.json?fields=code,product_name,brands,categories,ingredients_text,allergens,serving_size,nutriments`;const r=await fetch(url,{headers:{Accept:"application/json"}});if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json(),p=d.product;if(d.status===1&&p){fill({jan,name:p.product_name,maker:p.brands,category:p.categories,ingredients:p.ingredients_text,allergens:p.allergens,nutrition:nutrition(p),portion:p.serving_size,source:`Open Food Facts／取得 ${new Date().toLocaleDateString("ja-JP")}／商品ラベル優先`});setStatus("scanState","商品を発見","success");$("productLookupResult").innerHTML='<div class="panel save-success">✓ 商品情報を取得しました。現物ラベルと照合してください。</div>'}else{setStatus("scanState","未登録","failure");$("productLookupResult").innerHTML='<div class="panel"><h3>商品が見つかりませんでした</h3><p>下のラベルOCRまたは手入力で登録できます。</p></div>'}}
 catch(e){setStatus("scanState","通信エラー","failure");$("productLookupResult").innerHTML=`<div class="panel">検索できませんでした（${escapeHtml(e.message)}）。OCR・手入力は使用できます。</div>`}}
async function stop(){if(scanner?.isScanning)await scanner.stop().catch(()=>{});$("barcodeReader").hidden=true;$("stopBarcode").hidden=true;$("startBarcode").hidden=false}
async function start(){if(!window.Html5Qrcode)return alert("読取機能を読み込めませんでした。");await stop();$("barcodeReader").hidden=false;$("stopBarcode").hidden=false;$("startBarcode").hidden=true;setStatus("scanState","カメラ起動中","working");scanner=new Html5Qrcode("barcodeReader",{formatsToSupport:[Html5QrcodeSupportedFormats.EAN_13,Html5QrcodeSupportedFormats.EAN_8,Html5QrcodeSupportedFormats.UPC_A,Html5QrcodeSupportedFormats.UPC_E]});try{await scanner.start({facingMode:{ideal:"environment"}},{fps:12,aspectRatio:1.333},async code=>{navigator.vibrate?.(120);await stop();lookup(code)},()=>{});setStatus("scanState","バーコードを画面内へ","working")}catch(e){await stop();setStatus("scanState","カメラ使用不可","failure");alert("Safariのサイト設定でカメラを許可するか、JANを手入力してください。")}}
async function ocrEngine(){if(worker)return worker;if(!window.Tesseract)throw Error("OCR機能を読み込めませんでした");worker=await Tesseract.createWorker("jpn",1,{workerPath:"./vendor/worker.min.js",corePath:"./vendor/tesseract-core",langPath:"./vendor/lang",logger:m=>{const p=Math.round((m.progress||0)*100);$("ocrProgress").style.width=`${p}%`;$("ocrMessage").textContent=`OCR処理中：${m.status||"準備"} ${p}%`}});return worker}
async function runOcr(file,target){if(!file||busy)return;busy=true;setStatus("ocrState","文字認識中","working");const url=URL.createObjectURL(file);$("ocrPreview").src=url;$("ocrPreview").hidden=false;try{const w=await ocrEngine(),r=await w.recognize(file),text=String(r.data.text||"").replace(/[ \t]+/g," ").replace(/\n{3,}/g,"\n\n").trim();if(!text)throw Error("文字を認識できませんでした");$(target).value=text;setStatus("ocrState","認識完了・要確認","success");$("ocrMessage").textContent="結果を反映しました。誤字や数値をラベルと照合してください。";analyze()}catch(e){setStatus("ocrState","認識失敗","failure");$("ocrMessage").textContent=`${e.message}。明るい場所で正面から再撮影してください。`}finally{URL.revokeObjectURL(url);busy=false}}
function saveProduct(){const data=form();if(!data.name)return alert("商品名を入力してください。");if(data.jan&&!validJan(data.jan))return alert("JANコードを確認してください。");const item={...data,...analyze(),savedAt:new Date().toISOString()};const i=state.customProducts.findIndex(x=>(data.jan&&x.jan===data.jan)||x.name===data.name);if(i>=0)state.customProducts[i]=item;else state.customProducts.unshift(item);saveV10();renderCustomProducts();setStatus("scanState","保存完了","success");$("productLookupResult").innerHTML='<div class="panel save-success">✓ マイ商品DBへ保存しました。次回はJAN読取だけで表示します。</div>'}
$("startBarcode").onclick=start;$("stopBarcode").onclick=stop;$("janSearch").onclick=()=>lookup($("janInput").value);$("janInput").onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();lookup(e.target.value)}};$("ingredientsImage").onchange=e=>runOcr(e.target.files?.[0],"scanIngredients");$("nutritionImage").onchange=e=>runOcr(e.target.files?.[0],"scanNutrition");$("analyzeScannedProduct").onclick=analyze;$("saveScannedProduct").onclick=saveProduct;
["baseHb","baseAlt","baseUa"].forEach(id=>{const v=localStorage.getItem(`hc11.${id}`);if(v!==null)$(id).value=v});renderPrediction();
})();
